"""
Plan schema - describes what changed and what should be tested.

A Plan is the input to the evaluator pipeline. It can be generated by an LLM
analyzing a git diff, PR description, or code review.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class RiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ChangeType(str, Enum):
    FEATURE = "feature"
    BUGFIX = "bugfix"
    REFACTOR = "refactor"
    CONFIG = "config"
    PERFORMANCE = "performance"
    SCHEMA = "schema"
    RANKING = "ranking"
    FEEDING = "feeding"
    CONTAINER = "container"
    STORAGE = "storage"


@dataclass
class ChangedComponent:
    """A single component that was modified."""
    name: str
    change_type: ChangeType
    files_changed: list[str] = field(default_factory=list)
    description: str = ""


@dataclass
class TestSuggestion:
    """A suggestion for what should be tested."""
    category: str  # e.g., "search", "config", "container"
    area: str  # e.g., "basicsearch", "ranking", "deploy"
    reason: str = ""
    priority: int = 1  # 1=highest
    generate_new: bool = False  # whether to dynamically generate a case
    generation_hint: str = ""  # hint for case generator


@dataclass
class Plan:
    """
    Structured plan describing changes and required testing.

    Example:
        plan = Plan(
            summary="Modified ranking expression evaluation in searchcore",
            changed_components=[
                ChangedComponent(
                    name="searchcore/ranking",
                    change_type=ChangeType.RANKING,
                    files_changed=["searchcore/src/ranking/expression.cpp"],
                    description="Fixed edge case in tensor dot product"
                )
            ],
            risk_level=RiskLevel.HIGH,
            test_suggestions=[
                TestSuggestion(category="search", area="ranking", priority=1),
                TestSuggestion(
                    category="search", area="tensor",
                    generate_new=True,
                    generation_hint="Test tensor dot product with zero vectors"
                ),
            ]
        )
    """
    summary: str
    changed_components: list[ChangedComponent] = field(default_factory=list)
    risk_level: RiskLevel = RiskLevel.MEDIUM
    test_suggestions: list[TestSuggestion] = field(default_factory=list)
    affected_areas: list[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "summary": self.summary,
            "changed_components": [
                {
                    "name": c.name,
                    "change_type": c.change_type.value,
                    "files_changed": c.files_changed,
                    "description": c.description,
                }
                for c in self.changed_components
            ],
            "risk_level": self.risk_level.value,
            "test_suggestions": [
                {
                    "category": s.category,
                    "area": s.area,
                    "reason": s.reason,
                    "priority": s.priority,
                    "generate_new": s.generate_new,
                    "generation_hint": s.generation_hint,
                }
                for s in self.test_suggestions
            ],
            "affected_areas": self.affected_areas,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict) -> Plan:
        return cls(
            summary=data["summary"],
            changed_components=[
                ChangedComponent(
                    name=c["name"],
                    change_type=ChangeType(c["change_type"]),
                    files_changed=c.get("files_changed", []),
                    description=c.get("description", ""),
                )
                for c in data.get("changed_components", [])
            ],
            risk_level=RiskLevel(data.get("risk_level", "medium")),
            test_suggestions=[
                TestSuggestion(
                    category=s["category"],
                    area=s["area"],
                    reason=s.get("reason", ""),
                    priority=s.get("priority", 1),
                    generate_new=s.get("generate_new", False),
                    generation_hint=s.get("generation_hint", ""),
                )
                for s in data.get("test_suggestions", [])
            ],
            affected_areas=data.get("affected_areas", []),
            metadata=data.get("metadata", {}),
        )

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str) -> Plan:
        return cls.from_dict(json.loads(json_str))
