"""
Dynamic test case generator - creates new test cases based on Plan hints.

Uses existing test cases as templates and the Vespa test DSL to generate
new cases targeting specific scenarios. This is where LLM integration
happens - the generator can call an LLM to produce test code.

Generation modes:
    1. Template-based: Clone an existing similar case and modify parameters
    2. LLM-generated: Use an LLM to write a new test from scratch
    3. Parametric: Generate variations of an existing test with different inputs
"""

from __future__ import annotations

import logging
import textwrap
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from ..core.plan import TestSuggestion
from ..core.test_case_index import TestCaseEntry, TestIndex, TestMethod

logger = logging.getLogger(__name__)


@dataclass
class GeneratedCase:
    """A dynamically generated test case."""
    file_path: str  # Where to write the generated test
    content: str  # Ruby source code
    entry: TestCaseEntry  # Index entry for the generated test
    based_on: str = ""  # FQN of the template case, if any
    generation_method: str = ""  # "template", "llm", "parametric"


# Template for generating a new search test case
SEARCH_TEST_TEMPLATE = textwrap.dedent("""\
    # Copyright Vespa.ai. All rights reserved.
    # Auto-generated by Vespa Evaluator
    require '{require_path}'

    class {class_name} < {parent_class}

      def setup
        set_owner("vespa-evaluator")
        set_description("{description}")
      end

      def timeout_seconds
        {timeout}
      end

      {test_methods}

    end
""")

# Map categories to their default parent class and require path
CATEGORY_DEFAULTS = {
    "search": ("IndexedOnlySearchTest", "indexed_only_search_test"),
    "config": ("ConfigTest", "config_test"),
    "container": ("ContainerTest", "container_test"),
    "docproc": ("DocprocTest", "docproc_test"),
    "vds": ("VdsTest", "vds_test"),
}


class CaseGenerator:
    """
    Generates new test cases from templates or LLM output.

    Usage:
        generator = CaseGenerator(
            index=index,
            output_dir="/tmp/vespa-eval-generated",
        )

        generated = generator.from_template(
            suggestion=TestSuggestion(
                category="search",
                area="ranking",
                generate_new=True,
                generation_hint="Test tensor dot product with zero vectors",
            )
        )
    """

    def __init__(
        self,
        index: TestIndex,
        output_dir: str | Path = "/tmp/vespa-eval-generated",
        llm_client=None,
    ):
        self.index = index
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.llm_client = llm_client

    def from_template(self, suggestion: TestSuggestion) -> GeneratedCase | None:
        """
        Generate a test case by finding a similar existing case and modifying it.
        """
        # Find the best template case
        template = self._find_template(suggestion)
        if not template:
            logger.warning(
                f"No template found for {suggestion.category}/{suggestion.area}"
            )
            return self._from_scratch(suggestion)

        # Read the template file
        # In production, this would read from the actual test repo
        class_name = f"Generated{suggestion.area.title().replace('_', '')}Test"
        suffix = uuid.uuid4().hex[:6]
        class_name = f"{class_name}_{suffix}"

        parent_class, require_path = CATEGORY_DEFAULTS.get(
            suggestion.category, ("SearchTest", "search_test")
        )

        test_method_code = textwrap.indent(
            textwrap.dedent(f"""\
                def test_generated_{suggestion.area}
                  # Generated based on: {template.fqn}
                  # Hint: {suggestion.generation_hint}
                  #
                  # TODO: This is a placeholder. In production, an LLM would
                  # generate the actual test logic based on the hint and template.
                  flunk("Generated test not yet implemented - needs LLM completion")
                end
            """),
            "  ",
        )

        content = SEARCH_TEST_TEMPLATE.format(
            require_path=require_path,
            class_name=class_name,
            parent_class=parent_class,
            description=suggestion.generation_hint or f"Generated test for {suggestion.area}",
            timeout=600,
            test_methods=test_method_code,
        )

        file_name = f"generated_{suggestion.area}_{suffix}.rb"
        file_path = self.output_dir / file_name

        entry = TestCaseEntry(
            file_path=str(file_path),
            class_name=class_name,
            parent_class=parent_class,
            owner="vespa-evaluator",
            description=suggestion.generation_hint,
            category=suggestion.category,
            area=suggestion.area,
            test_methods=[
                TestMethod(name=f"test_generated_{suggestion.area}", line_number=0)
            ],
            tags=["generated", suggestion.category],
        )

        return GeneratedCase(
            file_path=str(file_path),
            content=content,
            entry=entry,
            based_on=template.fqn,
            generation_method="template",
        )

    def _from_scratch(self, suggestion: TestSuggestion) -> GeneratedCase:
        """Generate a minimal test case from scratch when no template exists."""
        suffix = uuid.uuid4().hex[:6]
        class_name = f"GeneratedTest_{suffix}"
        parent_class, require_path = CATEGORY_DEFAULTS.get(
            suggestion.category, ("SearchTest", "search_test")
        )

        test_method_code = textwrap.indent(
            textwrap.dedent(f"""\
                def test_generated
                  # Hint: {suggestion.generation_hint}
                  flunk("Generated test not yet implemented - needs LLM completion")
                end
            """),
            "  ",
        )

        content = SEARCH_TEST_TEMPLATE.format(
            require_path=require_path,
            class_name=class_name,
            parent_class=parent_class,
            description=suggestion.generation_hint or "Auto-generated test",
            timeout=600,
            test_methods=test_method_code,
        )

        file_name = f"generated_scratch_{suffix}.rb"
        file_path = self.output_dir / file_name

        entry = TestCaseEntry(
            file_path=str(file_path),
            class_name=class_name,
            parent_class=parent_class,
            owner="vespa-evaluator",
            description=suggestion.generation_hint,
            category=suggestion.category,
            area=suggestion.area,
            test_methods=[TestMethod(name="test_generated", line_number=0)],
            tags=["generated", suggestion.category],
        )

        return GeneratedCase(
            file_path=str(file_path),
            content=content,
            entry=entry,
            generation_method="scratch",
        )

    async def from_llm(self, suggestion: TestSuggestion) -> GeneratedCase | None:
        """
        Use an LLM to generate a complete test case.

        Provides the LLM with:
            - The test suggestion and generation hint
            - Similar existing test cases as examples (few-shot)
            - The Vespa test DSL documentation
        """
        if not self.llm_client:
            logger.warning("No LLM client configured, falling back to template")
            return self.from_template(suggestion)

        # Find similar cases for few-shot examples
        examples = self._find_examples(suggestion, max_examples=3)

        prompt = self._build_llm_prompt(suggestion, examples)

        # Call LLM (interface matches Anthropic SDK)
        response = await self.llm_client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=4096,
            messages=[{"role": "user", "content": prompt}],
        )

        generated_code = self._extract_ruby_code(response.content[0].text)
        if not generated_code:
            logger.error("LLM did not produce valid Ruby code")
            return self.from_template(suggestion)

        suffix = uuid.uuid4().hex[:6]
        file_name = f"generated_llm_{suggestion.area}_{suffix}.rb"
        file_path = self.output_dir / file_name

        # Parse the generated code to extract class info
        import re
        class_match = re.search(r"class\s+(\w+)\s*<\s*(\w+)", generated_code)
        class_name = class_match.group(1) if class_match else f"LLMGenerated_{suffix}"
        parent_class = class_match.group(2) if class_match else "SearchTest"

        methods = re.findall(r"def\s+(test_\w+)", generated_code)

        entry = TestCaseEntry(
            file_path=str(file_path),
            class_name=class_name,
            parent_class=parent_class,
            owner="vespa-evaluator",
            description=suggestion.generation_hint,
            category=suggestion.category,
            area=suggestion.area,
            test_methods=[TestMethod(name=m) for m in methods],
            tags=["generated", "llm", suggestion.category],
        )

        return GeneratedCase(
            file_path=str(file_path),
            content=generated_code,
            entry=entry,
            generation_method="llm",
        )

    def _find_template(self, suggestion: TestSuggestion) -> TestCaseEntry | None:
        """Find the best existing test case to use as a template."""
        # Try exact area match first
        matches = self.index.find_by_area(suggestion.category, suggestion.area)
        if matches:
            return matches[0]

        # Try category match
        matches = self.index.find_by_category(suggestion.category)
        if matches:
            return matches[0]

        # Try text search
        matches = self.index.search(suggestion.area)
        return matches[0] if matches else None

    def _find_examples(
        self, suggestion: TestSuggestion, max_examples: int = 3
    ) -> list[TestCaseEntry]:
        """Find similar test cases for few-shot LLM prompting."""
        results = []
        # First try exact area
        results.extend(self.index.find_by_area(suggestion.category, suggestion.area))
        # Then try text search on the hint
        if suggestion.generation_hint:
            results.extend(self.index.search(suggestion.generation_hint))
        # Deduplicate
        seen = set()
        unique = []
        for r in results:
            if r.fqn not in seen:
                unique.append(r)
                seen.add(r.fqn)
        return unique[:max_examples]

    def _build_llm_prompt(
        self, suggestion: TestSuggestion, examples: list[TestCaseEntry]
    ) -> str:
        """Build the prompt for LLM test generation."""
        examples_text = ""
        for ex in examples:
            examples_text += f"\n# Example: {ex.fqn} ({ex.description})\n"
            examples_text += f"# File: {ex.file_path}\n"
            examples_text += f"# Methods: {', '.join(m.name for m in ex.test_methods)}\n"

        return textwrap.dedent(f"""\
            Generate a Vespa system test case in Ruby.

            Category: {suggestion.category}
            Area: {suggestion.area}
            Requirement: {suggestion.generation_hint}

            The test should use the Vespa system test framework:
            - Inherit from the appropriate base class
            - Use set_owner("vespa-evaluator") and set_description(...)
            - Deploy an app using SearchApp DSL
            - Feed documents and assert results
            - Use assert_hitcount, assert_result for validation

            Similar existing tests for reference:
            {examples_text}

            Generate ONLY the Ruby code, wrapped in ```ruby``` markers.
        """)

    def _extract_ruby_code(self, text: str) -> str | None:
        """Extract Ruby code block from LLM response."""
        import re
        match = re.search(r"```ruby\s*\n(.*?)```", text, re.DOTALL)
        return match.group(1).strip() if match else None

    def write_generated(self, case: GeneratedCase):
        """Write a generated case to disk."""
        path = Path(case.file_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(case.content)
        logger.info(f"Wrote generated test to {case.file_path}")
